### ISSUE TITLE
DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#116]
error in browser:
```
xhr.js:45 Uncaught (in promise) DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at dispatchXhrRequest (http://34.226.147.197:4000/App.d36a57b6.js:24852:13)
    at new Promise (<anonymous>)
    at xhrAdapter (http://34.226.147.197:4000/App.d36a57b6.js:24821:10)
    at dispatchRequest (http://34.226.147.197:4000/App.d36a57b6.js:25462:10)

App.js:6 WebSocket connection to 'ws://34.226.147.197:33265/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
```
þetta kemur allaf þegar þetta startar á http://34.226.147.197:4000/

utils.js
```
const apiUrl = `${process.env.GAME_API_URL}:${process.env.GAME_API_PORT}`;
console.log(apiUrl);
```
sem output-ar 
﻿
34.226.147.197:3000

http://34.226.147.197:3000/status
returnar The api is running!

er þetta rangt url hjá mér?

**Comment by eythoro16** [comment]
```
17:41:20.029 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://35.173.252.218/state. (Reason: CORS request did not succeed).[Learn More]
17:41:27.091 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://35.173.252.218/guess21OrUnder. (Reason: CORS request did not succeed).[Learn More]
17:41:27.594 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://35.173.252.218/guessOver21. (Reason: CORS request did not succeed).[Learn More]
17:41:41.294 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://35.173.252.218/guess21OrUnder. (Reason: CORS request did not succeed).[Learn More]
```
firefox showed me the way

**Comment by eythoro16** [comment]
ætti ekki að vera nó að setja 

```
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```
í server.js?

**Comment by eythoro16** [comment]
lagaði þetta.

**Comment by isabellaf16** [comment]
Hvernig lagaðiru þetta? Erum að fá sömu villu

**Comment by skulia15** [comment]
ég er að lenda í þessu sama, gætiru sagt mér hvað þú gerðir til að laga þessa villu?
