### ISSUE TITLE
Game-client kóðinn keyrir ekki (Day 12, connect UI)

### ISSUE THREAD

**Issue by eddast** [hgop/syllabus-2018#79]
Þurfti í fyrsta lagi að færa index.js skránna inn í src/ möppuna úr game-client rótarmöppunni því hún var á vitlausum stað (þ.e. index.html var að reference-a index.js frá src/index.js) og þurfti að uppfæra package.json samkvæmt því.

Í öðru lagi fæ ég alltaf þessa villu þegar ég keyri upp:
```
game_client_1_8096b56dad80 | > lucky-21-frontend@1.0.0 start /code
game_client_1_8096b56dad80 | > node ./src/index.js
game_client_1_8096b56dad80 |
game_client_1_8096b56dad80 | 🚨  /code/node_modules/parcel-bundler/src/Bundler.js: unknown Statement of type "ForOfStatement"
game_client_1_8096b56dad80 |     at Emitter.Ep.explodeStatement (/code/node_modules/regenerator-transform/lib/emit.js:587:13)
game_client_1_8096b56dad80 |     at /code/node_modules/regenerator-transform/lib/emit.js:323:12
game_client_1_8096b56dad80 |     at Array.forEach (<anonymous>)
game_client_1_8096b56dad80 |     at Emitter.Ep.explodeStatement (/code/node_modules/regenerator-transform/lib/emit.js:322:22)
game_client_1_8096b56dad80 |     at Emitter.Ep.explodeStatement (/code/node_modules/regenerator-transform/lib/emit.js:510:12)
game_client_1_8096b56dad80 |     at /code/node_modules/regenerator-transform/lib/emit.js:323:12
game_client_1_8096b56dad80 |     at Array.forEach (<anonymous>)
game_client_1_8096b56dad80 |     at Emitter.Ep.explodeStatement (/code/node_modules/regenerator-transform/lib/emit.js:322:22)
game_client_1_8096b56dad80 |     at Emitter.<anonymous> (/code/node_modules/regenerator-transform/lib/emit.js:542:14)
game_client_1_8096b56dad80 |     at LeapManager.LMp.withEntry (/code/node_modules/regenerator-transform/lib/leap.js:143:14)
game_client_1_8096b56dad80 | ⚠️  /code/node_modules/parcel-bundler/lib/utils/generateCertificate.js:18:71: Cannotstatically evaluate fs argument
game_client_1_8096b56dad80 |   16 |
game_client_1_8096b56dad80 |   17 |   if (options.cache) {
game_client_1_8096b56dad80 | > 18 |     const cachedKey = fs.existsSync(privateKeyPath) && fs.readFileSync(privateKeyPath);
game_client_1_8096b56dad80 |      |                                                                       ^
game_client_1_8096b56dad80 |   19 |     const cachedCert = fs.existsSync(certPath) && fs.readFileSync(certPath);
game_client_1_8096b56dad80 |   20 |
game_client_1_8096b56dad80 |   21 |     if (cachedKey && cachedCert) {
game_client_1_8096b56dad80 | ⚠️  /code/node_modules/parcel-bundler/lib/utils/generateCertificate.js:19:66: Cannotstatically evaluate fs argument
game_client_1_8096b56dad80 |   17 |   if (options.cache) {
game_client_1_8096b56dad80 |   18 |     const cachedKey = fs.existsSync(privateKeyPath) && fs.readFileSync(privateKeyPath);
game_client_1_8096b56dad80 | > 19 |     const cachedCert = fs.existsSync(certPath) && fs.readFileSync(certPath);
game_client_1_8096b56dad80 |      |                                                                  ^
game_client_1_8096b56dad80 |   20 |
game_client_1_8096b56dad80 |   21 |     if (cachedKey && cachedCert) {
game_client_1_8096b56dad80 |   22 |       return {
game_client_1_8096b56dad80 | ⚠️  Could not load existing sourcemap of "../node_modules/parcel-bundler/lib/packagers/JSPackager.js".
game_client_1_8096b56dad80 | ⚠️  Could not load existing sourcemap of "../node_modules/parcel-bundler/lib/packagers/JSConcatPackager.js".
game_client_1_8096b56dad80 | ⚠️  /code/node_modules/dotenv/lib/main.js:63:41: Cannot statically evaluate fs argument
game_client_1_8096b56dad80 |   61 |   try {
game_client_1_8096b56dad80 |   62 |     // specifying an encoding returns a string instead of a buffer
game_client_1_8096b56dad80 | > 63 |     const parsed = parse(fs.readFileSync(dotenvPath, { encoding }))
game_client_1_8096b56dad80 |      |                                         ^
game_client_1_8096b56dad80 |   64 |
game_client_1_8096b56dad80 |   65 |     Object.keys(parsed).forEach(function (key) {
game_client_1_8096b56dad80 |   66 |       if (!process.env.hasOwnProperty(key)) {
game_client_1_8096b56dad80 | ⚠️  /code/node_modules/mime/mime.js:52:32: Cannot statically evaluate fs argument
game_client_1_8096b56dad80 |   50 |   // Read file and split into lines
game_client_1_8096b56dad80 |   51 |   var map = {},
game_client_1_8096b56dad80 | > 52 |       content = fs.readFileSync(file, 'ascii'),
game_client_1_8096b56dad80 |      |                                ^
game_client_1_8096b56dad80 |   53 |       lines = content.split(/[\r\n]+/);
game_client_1_8096b56dad80 |   54 |
game_client_1_8096b56dad80 |   55 |   lines.forEach(function(line) {
```

Henni finn ég ekki út úr. Reyndi að bæta við babel-core ^7 sem er eitthvað sem Google sagði að gæti verið að, en án árangurs. Reyndi líka að taka map fallið út án árángurs. Hvað þarf að laga/gera?

Also, er lýsingin fyrir connect UI fyrir dag 12 fullgerð?

**Comment by eddast** [comment]
OK komnir 5 tímar er að vera geðveik hjáááááááááálp.................

**Comment by skulia15** [comment]
Ég lendi í sömu villu

**Comment by kthorri** [comment]
Eina breytingin sem þarf er að reference'a App.js í html skjalinu, en ekki index.js.

Er búinn að pusha breytingum á repoið

**Comment by eddast** [comment]
Eraðfokkímééréréérérér...... takk
