### ISSUE TITLE
database.insertResult is not a function

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#85]
Þegar ég prófa capacity testið þá fæ ég pass. En ég fæ samt á tvemum console.log-um

```
  console.log server.lib-test.js:38
    guess: 500 - <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <title>Error</title>
    </head>
    <body>
    <pre>TypeError: database.insertResult is not a function<br> &nbsp; &nbsp;at app.post (/code/server.js:137:20)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/code/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /code/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/code/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at expressInit (/code/node_modules/express/lib/middleware/init.js:40:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)</pre>
    </body>
    </html>

```
```

  console.log server.lib-test.js:38
    guess: 500 - <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <title>Error</title>
    </head>
    <body>
    <pre>TypeError: database.insertResult is not a function<br> &nbsp; &nbsp;at app.post (/code/server.js:137:20)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/code/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /code/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/code/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at expressInit (/code/node_modules/express/lib/middleware/init.js:40:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)</pre>
    </body>
    </html>

```

**Comment by eythoro16** [comment]
þetta er samt mest allt sem var copy paste-að

**Comment by IronPeak** [comment]
database-inn hefur ekki verið rétt integrated í projectið þegar þú varst að setja upp dependency injection.
context('database') skilar databaseConstructor þarft að passa að kalla á constructorinn og nota objectið(databaseinn) sem kemur útúr því.
