### ISSUE TITLE
API Test Job - vesen

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#92]
jenkins config
```
rm -rf repository
git clone git@github.com:eythoro16/HGOP.git repository
cd repository
pwd

mkdir -p /var/lib/jenkins/terraform/hgop/apitest
rm -f /var/lib/jenkins/terraform/hgop/apitest/*.tf
cp *.tf /var/lib/jenkins/terraform/hgop/apitest/

mkdir -p /var/lib/jenkins/terraform/hgop/apitest/scripts
cp scripts/initialize_game_api_instance.sh /var/lib/jenkins/terraform/hgop/apitest/scripts/
cp scripts/docker_compose_up.sh /var/lib/jenkins/terraform/hgop/apitest/scripts/
cp docker-compose.yml /var/lib/jenkins/terraform/hgop/apitest/

cd /var/lib/jenkins/terraform/hgop/apitest
terraform init
terraform destroy -auto-approve -var environment=apitest || exit 1
terraform apply -auto-approve -var environment=apitest || exit 1
export API_URL=http://$(terraform output public_ip):3000

cd /var/lib/jenkins/workspace/api-test-hgop/repository/game-api
ls
npm install || exit 1
npm run test:api || exit 1
cd /var/lib/jenkins/terraform/hgop/apitest
terraform destroy -auto-approve -var environment=apitest || exit 1

exit 0
```
package.json
`"test:api": "jest --testRegex .*\\.api-test\\. --collectCoverage true",`

output
```
+ npm run test:api

> web@1.0.0 test:api /var/lib/jenkins/workspace/api-test-hgop/repository/game-api
> jest --testRegex .*\.api-test\. --collectCoverage true

FAIL ./server.capacity-test.js
  ● play 10 games within 30 seconds

    connect ECONNREFUSED 34.235.145.70:3000



FAIL ./server.api-test.js
  ● play a game

    connect ECONNREFUSED 34.235.145.70:3000



PASS ./lucky21.unit-test.js

PASS ./dealer.unit-test.js
PASS ./deck.unit-test.js
PASS ./random.unit-test.js
FAIL ./dealer.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./inject.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./server.lib-test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./random.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./app.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./package.json
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./.eslintrc.json
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./context.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./package-lock.json
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./deck.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./server.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./database.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./lucky21.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

FAIL ./config.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 16 failed, 4 passed, 20 total
Tests:       2 failed, 35 passed, 37 total
Snapshots:   0 total
Time:        4.9s
Ran all test suites.

Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

```
fatta ekki alvega hvað ég er að gera vitlaust. Af hverju reyni hann að testa alla file-anna? ég er búinn að prófa þetta locally og það virkaði.

er einhver með einhverja hugmynd?

**Comment by IronPeak** [comment]
Prófaðu að hafa testRegex: `.*\\.api-test\\.js`

**Comment by eythoro16** [comment]
skal segja þér hvernig það fór. tekur sinn tíma að builda stundum

**Comment by eythoro16** [comment]
virkaði en fæ

```
FAIL ./server.api-test.js
  ✕ play a game (18ms)

  ● play a game

    connect ECONNREFUSED 34.239.116.41:3000

```

**Comment by devalberg** [comment]
I inserted
```
sleep 5 ; npm run test:api
```
and it worked, seems like the database was not up and running and the test was trying to connect.

Seems like a hacky way... maybe there is a better way to let it load.

**Comment by eythoro16** [comment]
Thanks for the tip.
Am I wrong for thinking, that
```
ssh -o StrictHostKeyChecking=no -i "~/.aws/GameKeyPair.pem" ubuntu@$(terraform output public_ip) "./initialize_game_api_instance.sh" || exit 1

ssh -o StrictHostKeyChecking=no -i "~/.aws/GameKeyPair.pem" ubuntu@$(terraform output public_ip) "./docker_compose_up.sh $GIT_COMMIT" || exit 1
```
is needed in these two test pipelines? otherwise it wouldn't run docker-compose up right?

**Comment by devalberg** [comment]
Yeah I think you are right, otherwise docker wont be running anything

**Comment by eythoro16** [comment]
thanks for the late night help, can now continue with day 12
