### ISSUE TITLE
remove initialization part from database.js

### ISSUE THREAD

**Issue by eythoro16** [hgop/syllabus-2018#94]
```
module.exports = function(context) {
  const Client = context('pgClient');
  const configConstructor = context('config');
  const config = configConstructor(context);

  const getClient = () => new Client({
    host: config.pgHost,
    user: config.pgUser,
    password: config.pgPassword,
    database: config.pgDatabase,
  });

  // const client = getClient();
  // setTimeout(() =>
  //   client.connect((err) => {
  //     if (err) {
  //       console.log('failed to connect to postgres!');
  //     } else {
  //       console.log('successfully connected to postgres!');
  //       client.query('CREATE TABLE IF NOT EXISTS GameResult (ID SERIAL PRIMARY KEY, Won BOOL NOT NULL, Score INT NOT '
  //                  + 'NULL, Total INT NOT NULL, InsertDate TIMESTAMP NOT NULL);', (err) => {
  //         if (err) {
  //           console.log('error creating game result table!');
  //         } else {
  //           console.log('successfully created game result table!');
  //         }
  //         client.end();
  //       });
  //     }
  //   }), 5000);
  return {...
```

**Comment by IronPeak** [comment]
Já þetta er parturinn sem átti að taka út.

**Comment by eythoro16** [comment]
er að taka eftir því að þetta er ekki að runna eftir breyttingar, tengist ekki þessu.
við
`CMD sleep 5 && npm run migratedb:pg && node app.js`
þá fæ ég `db-migrate:not found`

**Comment by eythoro16** [comment]
```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "test:unit": "jest --testRegex .*\\.unit-test\\.js --collectCoverage true",
    "test:api": "jest --testRegex .*\\.api-test\\.js --collectCoverage true",
    "test:capacity": "jest --testRegex .*\\.capacity-test\\.js --collectCoverage true",
    "eslint": "eslint \"**/*.js\" --ignore-pattern '/node_modules/'",
    "eslint:fix": "eslint \"**/*.js\" --ignore-pattern '/node_modules/' --fix",
    "migratedb:pg": "db-migrate --verbose --env pg --config ./database.json --migrations-dir ./migrations up"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "db-migrate-pg": "^0.4.0",
    "express": "^4.16.2",
    "pg": "^7.6.1"
  },
  "devDependencies": {
    "eslint": "^5.9.0",
    "jest": "^23.6.0"
  }
}
```

**Comment by eythoro16** [comment]
`COPY /migrations/20181212041312-GameResultTable.js /migrations/20181212041312-GameResultTable.js`
er það rangt að hafa þetta svona í dockerfile? á kanski ekki að setja þetta í migrations folder

**Comment by IronPeak** [comment]
myndi búast við því að hún myndi lenda í rótinni á file systeminu inní docker :)

**Comment by eythoro16** [comment]
oko. Finn samt ekki útur því af hverju ég fæ 

```
my_game_api_1            | 
my_game_api_1            | > web@1.0.0 migratedb:pg /code
my_game_api_1            | > db-migrate --verbose --env pg --config ./database.json --migrations-dir ./migrations up
my_game_api_1            | 
my_game_api_1            | sh: 1: db-migrate: not found
my_game_api_1            | npm ERR! file sh
my_game_api_1            | npm ERR! code ELIFECYCLE
my_game_api_1            | npm ERR! errno ENOENT
my_game_api_1            | npm ERR! syscall spawn
my_game_api_1            | npm ERR! web@1.0.0 migratedb:pg: `db-migrate --verbose --env pg --config ./database.json --migrations-dir ./migrations up`
my_game_api_1            | npm ERR! spawn ENOENT
my_game_api_1            | npm ERR! 
my_game_api_1            | npm ERR! Failed at the web@1.0.0 migratedb:pg script.
my_game_api_1            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
my_game_api_1            | 
my_game_api_1            | npm ERR! A complete log of this run can be found in:
my_game_api_1            | npm ERR!     /root/.npm/_logs/2018-12-12T16_11_45_246Z-debug.log
```

**Comment by eythoro16** [comment]
![image](https://user-images.githubusercontent.com/24224443/49883868-6ff24f80-fe2b-11e8-8e28-0d8c1a248aa4.png)
Prófaði þetta líka að breyta þessu í  `"migratedb:pg": "node node_modules/db-migrate/bin/db-migrate --verbose --env pg --config ./database.json --migrations-dir ./migrations up"`
fæ þá 
```
my_game_api_1            | 
my_game_api_1            | > web@1.0.0 migratedb:pg /code
my_game_api_1            | > node node_modules/db-migrate/bin/db-migrate --verbose --env pg --config ./database.json --migrations-dir ./migrations up
my_game_api_1            | 
my_game_api_1            | internal/modules/cjs/loader.js:582
my_game_api_1            |     throw err;
my_game_api_1            |     ^
my_game_api_1            | 
my_game_api_1            | Error: Cannot find module '/code/node_modules/db-migrate/bin/db-migrate'
my_game_api_1            |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
my_game_api_1            |     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
my_game_api_1            |     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
my_game_api_1            |     at startup (internal/bootstrap/node.js:285:19)
my_game_api_1            |     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
my_game_api_1            | npm ERR! code ELIFECYCLE
my_game_api_1            | npm ERR! errno 1
my_game_api_1            | npm ERR! web@1.0.0 migratedb:pg: `node node_modules/db-migrate/bin/db-migrate --verbose --env pg --config ./database.json --migrations-dir ./migrations up`
my_game_api_1            | npm ERR! Exit status 1
my_game_api_1            | npm ERR! 
my_game_api_1            | npm ERR! Failed at the web@1.0.0 migratedb:pg script.
my_game_api_1            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
my_game_api_1            | 
my_game_api_1            | npm ERR! A complete log of this run can be found in:
my_game_api_1            | npm ERR!     /root/.npm/_logs/2018-12-12T16_31_15_593Z-debug.log
hgop_my_game_api_1 exited with code 1
```

**Comment by IronPeak** [comment]
það vantar db-migrate í package.json hjá þér

**Comment by eythoro16** [comment]
af hverju er `npm install db-migrate` að installa package sem heitir db-migrate-pg. ætti það ekki að vera package db-migrate

**Comment by eythoro16** [comment]
fuck ég er hálviti. ég runnaði npm `install db-migrate-pg --save` og `install db-migrate` en gleymdi --save

**Comment by eythoro16** [comment]
follow up question: `Now create another migration script that adds the InsertDate column to the GameResult table.`  á þá að runna `node node_modules/db-migrate/bin/db-migrate --env pg create InsertDate`

**Comment by IronPeak** [comment]
já þið eigið að búa til aðra migration scriptu sem sér um það

**Comment by eythoro16** [comment]
önnur followup spurning: þurfum við ekki annars að breytta database.json til dæmis að
```
{
    "pg": {
      "driver": "pg",
      "host": "my_database_container", --> ætti að vera það sama og í docker-compose.yml
      "database": "game_database", --> ætti að vera það sama og í docker-compose.yml
      "user": "my_user", --> ætti að vera það sama og í docker-compose.yml
      "password": "my_password", --> ætti að vera það sama og í docker-compose.yml
      "schema": "postgres",
      "port": 5432,
      "max": 10,
      "idleTimeoutMillis": 30000
    }
  }
``` 
eða á að gera það öfugt

**Comment by eythoro16** [comment]
nevermind breytti docker-compose heitin þannig að þau eru eins í week 2 solution
